FROM node:18-alpine

WORKDIR /usr/src/app

# Install app dependencies
COPY package*.json ./
COPY prisma ./prisma/

# Install all dependencies with --legacy-peer-deps to fix version conflicts
RUN npm install --legacy-peer-deps

# Generate Prisma client
RUN npx prisma generate

# Copy app source code
COPY . .


# Expose the app port
EXPOSE 3000

# Start the app in development mode
CMD ["npm", "run", "start:dev"]
